language: go

go:
  - "1.10.x"
  - master

install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure

jobs:
  include:
    - stage: test
      script: make test
