language: go

go:
  - "1.11"

install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure

# Override the default command which is "make"
script: make test 

jobs:
  include:
    - stage: test
      script: make test
